# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 04:11
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='clean_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, db_index=True, default=[], size=None),
            preserve_default=False,
        ),
    ]
